language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
#Download and compile dependencies
  - cd ExtLibs
  - sudo apt-get install p7zip-full
    #SFML dependencies:
  - sudo apt-get install libopenal-dev libjpeg-dev libglew-dev libudev-dev libxrandr-dev libsndfile1-dev libglu1-mesa-dev libfreetype6-dev
  - cd ..
#Compile the tests only
  - mkdir .build-tests
  - cd .build-tests
  - cmake -DBUILD_GDJS=FALSE -DBUILD_IDE=FALSE -DBUILD_EXTENSIONS=FALSE -DBUILD_TESTS=TRUE -DNO_GUI=TRUE ..
  - make -j 4
  - cd ..

script:
#  - export LD_LIBRARY_PATH=$PWD/Binaries/Output/Release_Linux:$PWD/.build-tests/ExtLibs/SFML/lib:$LD_LIBRARY_PATH
  - cd .build-tests
  - Core/GDCore_tests
  - GDCpp/GDCpp_tests
