language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
#Download and compile dependencies
  - sudo apt-get install p7zip-full
    #SFML dependencies:
  - sudo apt-get install libopenal-dev libjpeg-dev libglew-dev libudev-dev libxrandr-dev libsndfile1-dev libglu1-mesa-dev libfreetype6-dev
#Compile the tests only
  - mkdir .build-tests
  - cd .build-tests
  - cmake -DBUILD_GDJS=FALSE -DBUILD_IDE=FALSE -DBUILD_EXTENSIONS=FALSE -DBUILD_TESTS=TRUE -DNO_GUI=TRUE ..
  - make -j 4
  - cd ..
#Install GDJS tests dependencies
  - cd GDJS/tests
  - npm install
  - cd ../..

script:
#GDJS game engine tests:
  - cd GDJS/tests
  - npm test
  - cd ../..
#GDCore and GDCpp game engine tests:
  - cd .build-tests
# - export LD_LIBRARY_PATH=$PWD/Binaries/Output/Release_Linux:$PWD/.build-tests/ExtLibs/SFML/lib:$LD_LIBRARY_PATH
  - Core/GDCore_tests
  - GDCpp/GDCpp_tests